UNIFI:
  URLS:
    - https://192.168.1.1:8443
  # Map UniFi site "default" to NetBox site "Home"
  USE_SITE_MAPPING: false
  SITE_MAPPINGS:
    "default": "Home"

NETBOX:
  URL: http://netbox.network.svc.cluster.local
  ROLES:
    WIRELESS: wireless-ap
    LAN: switch
  TENANT: Home Network
