# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi2netbox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi2netbox-secret
  data:
    - secretKey: UNIFI_USER
      remoteRef:
        key: ubiquti
        property: username
    - secretKey: UNIFI_PASSWORD
      remoteRef:
        key: ubiquti
        property: password
    - secretKey: UNIFI_MFA_SECRET
      remoteRef:
        key: ubiquti
        property: totp_secret
    - secretKey: NETBOX_API_TOKEN
      remoteRef:
        key: netbox
        property: NETBOX_API
