# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./externalsecret.yaml
  - ./cronjob.yaml

configMapGenerator:
  - name: unifi2netbox-config
    files:
      - config/config.yaml
