---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbox-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://netbox-community.github.io/netbox-chart/
