# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-netbox-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: proxmox-netbox-sync-secret
  data:
    - secretKey: PVE_USER
      remoteRef:
        key: Proxmox Terraform
        property: api_user
    - secretKey: PVE_TOKEN_NAME
      remoteRef:
        key: Proxmox Terraform
        property: api_token_name
    - secretKey: PVE_TOKEN_VALUE
      remoteRef:
        key: Proxmox Terraform
        property: token_secret
    - secretKey: NB_TOKEN
      remoteRef:
        key: netbox
        property: NETBOX_API
