# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ../../../../templates/gatus/external
configMapGenerator:
  - name: pdlf-website-webroot
    files:
      - webroot/index.html
  - name: pdlf-website-nginx-config
    files:
      - nginx-config/nginx.conf
generatorOptions:
  disableNameSuffixHash: true
