---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./rbac.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./resources/puppet-lab.yaml
  - ./resources/infrastructure.yaml
  - ./resources/proxmox-hypervisors.yaml
  - ./resources/kubernetes-services.yaml
  - ../../../../templates/gatus/guarded
configMapGenerator:
  - name: gatus-configmap
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
