---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./minio/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./home-assistant/ks.yaml
  - ./nginx-reverse-proxy/ks.yaml
  - ./homepage/ks.yaml
  - ./reactive-resume/ks.yaml
  - ./pdlf-website/ks.yaml
  - ./scrypted/ks.yaml
  - ./paperless/ks.yaml
  - ./paperless-ai/ks.yaml
  - ./immich/ks.yaml
  #- ./penpot/ks.yaml
  - ./theme-park/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  # - ./nextcloud/ks.yaml
