---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shitbox-mqtt-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shitbox-mqtt-exporter
    template:
      data:
        # App
        # Mosquitto
        MQTT_USERNAME: "{{ .X_EMQX_MQTT_USERNAME }}"
        MQTT_PASSWORD: "{{ .X_EMQX_MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: emqx
