# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-netbox-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-netbox-sync-secret
  data:
    - secretKey: UNIFI_USERNAME
      remoteRef:
        key: unipoller
        property: username
    - secretKey: UNIFI_PASSWORD
      remoteRef:
        key: unipoller
        property: password
    - secretKey: NETBOX_TOKEN
      remoteRef:
        key: netbox
        property: NETBOX_API
