# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret_v1.json
---
# Dummy secret for Valkey (chart expects it even with auth disabled)
apiVersion: v1
kind: Secret
metadata:
  name: netbox-valkey
type: Opaque
stringData:
  valkey-password: ""
