---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: asciinema-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: asciinema-secret
    template:
      engineVersion: v2
      data:
        # Database credentials
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .ASCIINEMA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .ASCIINEMA_POSTGRES_PASS }}"
        INIT_POSTGRES_DBNAME: asciinema
        # Application secrets
        SECRET_KEY_BASE: "{{ .ASCIINEMA_SECRET_KEY_BASE }}"
        DATABASE_URL: "postgresql://{{ .ASCIINEMA_POSTGRES_USER }}:{{ .ASCIINEMA_POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local:5432/asciinema"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: asciinema
